name: 'Update Flake Inputs'
description: 'Creates pull requests for each flake input update on Gitea'
author: 'Your Name'

inputs:
  gitea-url:
    description: 'Gitea server URL'
    required: true
    default: ${{ gitea.server_url }}
  gitea-token:
    description: 'Gitea authentication token'
    required: true
    default: ${{ secrets.GITEA_TOKEN }}
  gitea-repository:
    description: 'Repository in format owner/repo'
    required: false
    default: ${{ gitea.repository }}
  exclude-patterns:
    description: 'Comma-separated list of glob patterns to exclude flake.nix files'
    required: false
    default: ''
  base-branch:
    description: 'Base branch to create PRs against'
    required: false
    default: 'main'
  auto-merge:
    description: 'Automatically merge PRs when checks succeed'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for avoiding rate limits when fetching flake inputs'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run update-flake-inputs
      shell: bash
      run: |
        AUTO_MERGE_FLAG=""
        if [[ "${{ inputs.auto-merge }}" == "true" ]]; then
          AUTO_MERGE_FLAG="--auto-merge"
        fi

        # Prepend GitHub access token to NIX_CONFIG if provided
        if [[ -n "${{ inputs.github-token }}" ]]; then
          if [[ -n "${NIX_CONFIG:-}" ]]; then
            export NIX_CONFIG="access-tokens = github.com=${{ inputs.github-token }} ${NIX_CONFIG}"
          else
            export NIX_CONFIG="access-tokens = github.com=${{ inputs.github-token }}"
          fi
        fi

        nix run github:Mic92/update-flake-inputs-gitea#update-flake-inputs -- \
          --gitea-url "${{ inputs.gitea-url }}" \
          --gitea-token "${{ inputs.gitea-token }}" \
          --gitea-repository "${{ inputs.gitea-repository }}" \
          --exclude-patterns "${{ inputs.exclude-patterns }}" \
          --base-branch "${{ inputs.base-branch }}" \
          $AUTO_MERGE_FLAG
